### PR TITLE
#165413059 Setup travis to run tests

### PR DESCRIPTION
**Pull request by AJAkimana**
Description
=======
This task is about setting up Travis as a continuous integration system and CodeClimate

Type of change
=======
N/A

How has it been tested
=======
- Visit this link [Travis Riders-ah-frontend](https://travis-ci.org/andela/riders-ah-frontend/builds/551389137)

Checklist:
=======
- Add configuration file for travis
- Add badges for Tracis and CodeClimate

Pivotal tracker story ID
=======
[165413059](https://www.pivotaltracker.com/n/projects/2326984/stories/165413059)

### CODE REVIEW

**Comment by macphilips** [comment]
@AJAkimana can you [`cherry-pick`](https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean) the commit from @Kabalisa PR: #6 to test this integration.

**Comment by Kabalisa** [comment]
@AJAkimana good job. it looks good to me except that the Travis badge is reading ```build: unknown``` even though the tests are passing.

**Comment by AJAkimana** [comment]
> @AJAkimana good job. it looks good to me except that the Travis badge is reading `build: unknown` even though the tests are passing.

It is because the badge is set to `develop` branch, take a look at [this branch badge](https://travis-ci.org/andela/riders-ah-frontend.svg?branch=ch-setup-travis-165413059)

**Comment by Kabalisa** [comment]
> > @AJAkimana good job. it looks good to me except that the Travis badge is reading `build: unknown` even though the tests are passing.
> 
> It is because the badge is set to `develop` branch, take a look at [this branch badge](https://travis-ci.org/andela/riders-ah-frontend.svg?branch=ch-setup-travis-165413059)

Ok. I see why now

**Review by Kabalisa — APPROVED** [review]

**Review by Niyitangasam — APPROVED** [review]

**Pull request merged**
